name: Build and push Docker image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
    
    - name: Login to Github Packages
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_PAT }}
        
    - name: Build image and push to ghcr
      uses: docker/build-push-action@v2
      with:
        context: .
        tags: ghcr.io/${{ github.actor }}/mtfg-angular:latest
        # build on feature branches, push only on main branch
        push: ${{ github.ref == 'refs/heads/main' }}

    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
